#!/usr/bin/perl
#
# Create an example multipart MIME message.
#
use strict;
use warnings;

use Email::MIME;
use IO::All;

my %header = (
    From => 'gene@ology.net',
    To   => 'gene.boggs@gmail.com',
    CC   => '',
);

=for private
# Multipart message
my @parts = (
    Email::MIME->create(
        attributes => {
        filename     => 'test.pdf',
        content_type => 'application/pdf',
        encoding     => 'quoted-printable',
        name         => 'Test PDF file',
    },
    body => io('test.pdf')->all,
    ),
    Email::MIME->create(
        body_str   => 'Testing!',
        attributes => {
            charset      => 'US-ASCII',
            content_type => 'text/plain',
            disposition  => 'attachment',
            encoding     => 'quoted-printable',
        },
    ),
);
=cut

my $email = Email::MIME->create(
    header_str => [ %header ],
    body => 'Testing!',
#    parts      => [ @parts ],
);

# Append headers:
$email->header_str_set( 'X-PoweredBy' => "Perl $]" );

# Nesting parts:
#$email->parts_set([
#    $email->parts,
#    Email::MIME->create( parts => [ @parts ] ),
#]);
# Encoding parts:
#if (@parts) {
#    $_->encoding_set( 'base64' ) for $email->parts;
#}

print $email->as_string;

