#!/usr/bin/perl
#
# Make sure SMPT email works.
# -- gene@cpan.org
#
use strict;
use warnings;

use Net::SMTP;
use Sys::Hostname; # XXX This may or may not be handy.

# Fetch/set parameters.
my %params = (
    to   => shift || usage(),
    from => shift || $ENV{USER} .'@'. hostname(),
    host => shift || 'mail.' . hostname(),
    subj => shift || 'Testing',
    body => shift || 'Testing Net::SMTP',
    date => scalar(localtime),
);

my $smtp = Net::SMTP->new(
    $params{host},
    Timeout => 60,
    Debug   => 1,
) or die( "Can't create Net::SMTP object for host: $params{host}" );

$smtp->verify($params{to});
$smtp->mail($params{from});
$smtp->to($params{to});
$smtp->data();
$smtp->datasend("Date: $params{date}\n");
$smtp->datasend("From: $params{from}\n");
$smtp->datasend("To: $params{to}\n");
$smtp->datasend("Subject: $params{subj}\n");
$smtp->datasend("\n");
$smtp->datasend("$params{body}\n");
$smtp->dataend();
$smtp->quit;

sub usage {
    die "Usage: perl $0 to\@somehost [from\@yourhost mail.host 'Subject matter' 'Message body']\n";
}
